title: "Marbles App - A Private Space for Your Plans and Thoughts"
description: "All-in-one lightweight tool for keeping notes, managing lists and writing journals."
author: "Infonominal"
url: "https://yourmarbles.app"
baseurl: ""

# Build settings
markdown: kramdown
highlighter: rouge
# theme: minima  # Or remove if using custom

# Collections
collections:
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/
  - .bundle/
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/

# Include
include:
  - _pages
  - ml-confirmation-1.html
  - ml-confirmation-2.html

# Sass
sass:
  sass_dir: assets/stylesheets
