title: "Marbles - Your Private Space for Plans & Thoughts"
description: "All-in-one tool for journaling, tracking habits, managing simple lists and jotting down random thoughts."
author: "Infonominal"
url: "https://yourmarbles.app"
baseurl: ""

# Build settings
markdown: kramdown
highlighter: rouge
# theme: minima  # Or remove if using custom

# Collections
collections:
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/
  - .bundle/
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - ml-confirmation-1.html
  - ml-confirmation-2.html

# Include
include:
  - _pages

# Sass
sass:
  sass_dir: assets/stylesheets